export const GUESS_COUNT_INCREASE = "GUESS_COUNT_INCREASE";
export const GUESS_LETTER = "GUESS_LETTER";
export const SET_DISPLAY_VALUES = "SET_DISPLAY_VALUES";
export const SET_WORD_TO_GUESS = "SET_WORD_TO_GUESS";
export const START_GAME = "START_GAME";
export const RESET_GAME = "RESET_GAME"